In [2]:
import pandas as pd

In [3]:
data=pd.read_csv('preprocessed_train_data.csv')

In [4]:
data

PID                                          Text data  \
0         train_pid_1  waiting mind breakdown new year feeling isnt a...   
1         train_pid_2  new years resolution im gon na get ass therapi...   
2         train_pid_3  new year somone else feeling like 2020 last ye...   
3         train_pid_4  story guess hi im germany english mostly self ...   
4         train_pid_5     sat dark cried going new year great start 2020   
...               ...                                                ...   
11029  train_pid_5033      never want rely anyone lowkey always probably   
11030  train_pid_5051  anyone else feel like every single week dumb s...   
11031  train_pid_1722  well well im done cant believe im saying ive f...   
11032  train_pid_5373  thinking maxing two credit cards buy gaming la...   
11033  train_pid_5796  ive taking consistent showers last 2 weeks im ...   

                Label  
0            moderate  
1            moderate  
2            moderate  
3            moderate  
4            moderate  
...               ...  
11029  not depression  
11030  not depression  
11031  not depression  
11032  not depression  
11033  not depression  

[11034 rows x 3 columns]

In [5]:
data['Label'].value_counts()

moderate          3678
severe            3678
not depression    3678
Name: Label, dtype: int64

In [6]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer
x = data['Text data']
y = data['Label']
x = np.array(data.iloc[:,0].values)
y = np.array(data['Label'].values)
tfidf = TfidfVectorizer()
x = tfidf.fit_transform(data['Text data']).toarray()

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 0, shuffle = True)

In [9]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_recall_fscore_support as score
from sklearn.multiclass import OneVsRestClassifier
from sklearn.ensemble import RandomForestClassifier

In [8]:
rf = RandomForestClassifier(n_estimators=100 ,criterion='entropy' , random_state=0)
oneVsRestrf = OneVsRestClassifier(rf)
oneVsRestrf.fit(x_train, y_train)
y_pred = oneVsRestrf.predict(x_test)
accuracy = round(accuracy_score(y_test, y_pred) * 100, 2)
precision, recall, f1score, support = score(y_test, y_pred, average='micro')
print(f'Test Accuracy Score of Basic Random Forest: % {accuracy}')
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix")
print(cm)
from sklearn.metrics import classification_report
print("Classification Report")
print(classification_report(y_test,y_pred))
print(f'Precision : {precision}')
print(f'Recall : {recall}')
print(f'F1-score : {f1score}')

Test Accuracy Score of Basic Random Forest: % 84.48
Confusion Matrix
[[ 808  226   24]
 [ 226  899   12]
 [  24    2 1090]]
Classification Report
                precision    recall  f1-score   support

      moderate       0.76      0.76      0.76      1058
not depression       0.80      0.79      0.79      1137
        severe       0.97      0.98      0.97      1116

      accuracy                           0.84      3311
     macro avg       0.84      0.84      0.84      3311
  weighted avg       0.84      0.84      0.84      3311

Precision : 0.8447598912715192
Recall : 0.8447598912715192
F1-score : 0.8447598912715192


In [10]:
data=pd.read_csv('preprocessed_dev_data.csv')
data

Pid                                          text data  \
0        dev_pid_1  im scared lie every day say ill make think mig...   
1        dev_pid_2  new wanted vent finally realized im kind bad m...   
2        dev_pid_3  im sad kinda always issue wouldnt say bad peer...   
3        dev_pid_4  lonely alone immediately family members dead d...   
4        dev_pid_5  year trash dont know im posting dont even know...   
...            ...                                                ...   
6502  dev_pid_2514  anyone feared theyll kill loved ones sleep uni...   
6503  dev_pid_2829  finally got fulltime job feel even worse maybe...   
6504  dev_pid_2260  deal boredomnothing satisfying anymore days ta...   
6505  dev_pid_2653                   got bed showered morning removed   
6506  dev_pid_2460  depressed suicidal 2018 start 2020 ive woken d...   

        Class labels  
0           moderate  
1           moderate  
2           moderate  
3           moderate  
4           moderate  
...              ...  
6502  not depression  
6503  not depression  
6504  not depression  
6505  not depression  
6506  not depression  

[6507 rows x 3 columns]

In [11]:
data['Class labels'].value_counts()

moderate          2169
severe            2169
not depression    2169
Name: Class labels, dtype: int64

In [11]:
x = data['text data']
y = data['Class labels']
x = np.array(data.iloc[:,0].values)
y = np.array(data['Class labels'].values)
x = tfidf.fit_transform(data['text data']).toarray()

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 0, shuffle = True)

In [13]:
oneVsRestrf.fit(x_train, y_train)
y_pred = oneVsRestrf.predict(x_test)
accuracy = round(accuracy_score(y_test, y_pred) * 100, 2)
precision, recall, f1score, support = score(y_test, y_pred, average='micro')
print(f'Test Accuracy Score of Basic Random Forest: % {accuracy}')
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix")
print(cm)
from sklearn.metrics import classification_report
print("Classification Report")
print(classification_report(y_test,y_pred))
print(f'Precision : {precision}')
print(f'Recall : {recall}')
print(f'F1-score : {f1score}')

Test Accuracy Score of Basic Random Forest: % 92.99
Confusion Matrix
[[577  64   2]
 [ 71 574   0]
 [  0   0 665]]
Classification Report
                precision    recall  f1-score   support

      moderate       0.89      0.90      0.89       643
not depression       0.90      0.89      0.89       645
        severe       1.00      1.00      1.00       665

      accuracy                           0.93      1953
     macro avg       0.93      0.93      0.93      1953
  weighted avg       0.93      0.93      0.93      1953

Precision : 0.9298515104966718
Recall : 0.9298515104966718
F1-score : 0.9298515104966718


In [15]:
input_text = 'This is me. Don鈥檛 get me wrong, it鈥檚 better than don鈥檛-leave-my-bed-for-a-week depression. I am grateful I can be an independent person. But there is something uniquely horrible about being able to go to work every day, occasionally clean up after yourself, pay your bills, generally put yourself together enough to look like a human being... but that鈥檚 it. Nothing else. No social life. No hobbies. Constantly battling your mind. And being absolutely fucking exhausted all the time.'
preprocessed_text = tfidf.transform([input_text]).toarray()
prediction = oneVsRestrf.predict(preprocessed_text)
print(prediction)

['moderate']


In [16]:
data = pd.read_excel('test_data.xlsx')
data

Pid                                          Text data
0      test_id_1  This is me. Don鈥檛 get me wrong, it鈥檚 better th...
1      test_id_2  I hate that people don鈥檛 understand that i don...
2      test_id_3  But here I am, 24 years old man and doing exac...
3      test_id_4  I鈥檓 trapped inside. Does anyone else get that ...
4      test_id_5  I read a lot of posts on here of people strugg...
..           ...                                                ...
494  test_id_495  I'm 14\nmy mom doesn't take my mental health s...
495  test_id_496  I was quite shocked at their reactions. I sort...
496  test_id_497  Lying on my bed..... fantasising another life ...
497  test_id_498  I was bullied in elementary school, and I alwa...
498  test_id_499  I can't go on. Im after finishing a 26oz bottl...

[499 rows x 2 columns]

In [17]:
data['Text data'] = data['Text data'].fillna('')

In [18]:
pid = data['Pid']
text_data = data['Text data']

In [19]:
preprocessed_text = tfidf.transform(text_data).toarray()

In [20]:
predictions = oneVsRestrf.predict(preprocessed_text)

In [21]:
result_df = pd.DataFrame({'pid': pid, 'class_label': predictions})

In [22]:
result_df.to_csv('KEC_AI_NLP_DEP_english2.tsv', sep='\t', index=False)

In [23]:
data = pd.read_csv('KEC_AI_NLP_DEP_english2.tsv', sep='\t')
data

Pid                                          Text data  \
0      test_id_1  This is me. Don鈥檛 get me wrong, it鈥檚 better th...   
1      test_id_2  I hate that people don鈥檛 understand that i don...   
2      test_id_3  But here I am, 24 years old man and doing exac...   
3      test_id_4  I鈥檓 trapped inside. Does anyone else get that ...   
4      test_id_5  I read a lot of posts on here of people strugg...   
..           ...                                                ...   
494  test_id_495  I'm 14\nmy mom doesn't take my mental health s...   
495  test_id_496  I was quite shocked at their reactions. I sort...   
496  test_id_497  Lying on my bed..... fantasising another life ...   
497  test_id_498  I was bullied in elementary school, and I alwa...   
498  test_id_499  I can't go on. Im after finishing a 26oz bottl...   

    Prediction Output  
0            moderate  
1            moderate  
2      not depression  
3      not depression  
4            moderate  
..                ...  
494          moderate  
495          moderate  
496          moderate  
497          moderate  
498          moderate  

[499 rows x 3 columns]

In [24]:
data['class_label'].unique()

array(['moderate', 'not depression', 'severe'], dtype=object)

In [25]:
data['class_label'].value_counts()

moderate          401
not depression     97
severe              1
Name: Prediction Output, dtype: int64